steps:

- name: 'gcr.io/cloud-builders/docker'
  id: latest
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest',
    '.'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.7
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.7',
    'python3.7/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.8
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.8',
    '-t',
    'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.8',
    'python3.8/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.9
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.9',
    '-t',
    'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.9',
    'python3.9/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.10
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.10',
    '-t',
    'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.10',
    'python3.10/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.11
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.11',
    '-t',
    'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.11',
    'python3.11/'
  ]
  waitFor: ['-']

substitutions:
  _CLOUD_SDK_VERSION: '440.0.0'

images:
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.7'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.8'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.9'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.10'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.11'
  - 'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.8'
  - 'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.9'
  - 'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.10'
  - 'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.11'

timeout: 7200s
