steps:

- name: 'gcr.io/cloud-builders/docker'
  id: latest
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '--build-arg',
    'PYTHON_VERSION=3.7',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.7',
    'python/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.8
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '--build-arg',
    'PYTHON_VERSION=3.8',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.8',
    '-t',
    'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.8',
    'python/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.8-alpine
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '--build-arg',
    'PYTHON_VERSION=3.8',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.8-alpine',
    '-t',
    'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.8-alpine',
    'python-alpine/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.9
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '--build-arg',
    'PYTHON_VERSION=3.9',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.9',
    '-t',
    'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.9',
    'python/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.9-alpine
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '--build-arg',
    'PYTHON_VERSION=3.9',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.9-alpine',
    '-t',
    'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.9-alpine',
    'python-alpine/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.10
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '--build-arg',
    'PYTHON_VERSION=3.10',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.10',
    '-t',
    'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.10',
    'python/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.10-alpine
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '--build-arg',
    'PYTHON_VERSION=3.10',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.10-alpine',
    '-t',
    'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.10-alpine',
    'python-alpine/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.11
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '--build-arg',
    'PYTHON_VERSION=3.11',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.11',
    '-t',
    'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.11',
    'python/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.11-alpine
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '--build-arg',
    'PYTHON_VERSION=3.11',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.11-alpine',
    '-t',
    'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.11-alpine',
    'python-alpine/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.12
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '--build-arg',
    'PYTHON_VERSION=3.12',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.12',
    '-t',
    'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.12',
    'python/'
  ]
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: python3.12-alpine
  args: [
    'build',
    '--build-arg',
    'CLOUD_SDK_VERSION=${_CLOUD_SDK_VERSION}',
    '--build-arg',
    'PYTHON_VERSION=3.12',
    '-t',
    'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.12-alpine',
    '-t',
    'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.12-alpine',
    'python-alpine/'
  ]
  waitFor: ['-']

substitutions:
  _CLOUD_SDK_VERSION: '516.0.0'

images:
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.7'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.8'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.8-alpine'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.9'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.9-alpine'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.10'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.10-alpine'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.11'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.11-alpine'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.12'
  - 'gcr.io/$PROJECT_ID/github.com/globalfishingwatch/gfw-pipeline:latest-python3.12-alpine'
  - 'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.8'
  - 'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.8-alpine'
  - 'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.9'
  - 'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.9-alpine'
  - 'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.10'
  - 'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.10-alpine'
  - 'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.11'
  - 'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.11-alpine'
  - 'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.12'
  - 'us-east4-docker.pkg.dev/world-fishing-827/prj-ocean-soundscape/gfw-pipeline:latest-python3.12-alpine'

timeout: 7200s
